# Generated by Django 4.1.7 on 2023-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=13)),
                ('bg', models.CharField(max_length=3)),
                ('addline1', models.TextField()),
                ('addline2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('pwd', models.CharField(max_length=16)),
                ('city_ID', models.IntegerField(blank=True, null=True)),
                ('staff_ID', models.IntegerField(blank=True, null=True)),
                ('manager_ID', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=13)),
                ('bg', models.CharField(max_length=3)),
                ('addline1', models.TextField()),
                ('addline2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('pwd', models.CharField(max_length=16)),
                ('city_ID', models.IntegerField(blank=True, null=True)),
                ('staff_ID', models.IntegerField(blank=True, null=True)),
                ('manager_ID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
