# Generated by Django 4.1.7 on 2023-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hospital_bg_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
