# Generated by Django 4.1.7 on 2023-04-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_hospital_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=122)),
                ('hosp_name', models.CharField(max_length=122)),
                ('hosp_email', models.CharField(max_length=122)),
                ('time', models.TimeField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
