# Generated by Django 4.1.7 on 2023-04-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
