# Generated by Django 4.1.7 on 2023-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='medical_records',
            field=models.TextField(blank=True, null=True),
        ),
    ]
