# Generated by Django 4.1.7 on 2023-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_donor_medical_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=122)),
                ('hosp_name', models.CharField(max_length=122)),
                ('hosp_email', models.CharField(max_length=122)),
                ('time', models.TimeField()),
                ('date', models.DateField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
