# Generated by Django 4.1.7 on 2023-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_blood_group_remove_hospital_bg_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_group',
            name='ABneg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blood_group',
            name='ABpos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blood_group',
            name='Aneg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blood_group',
            name='Apos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blood_group',
            name='Bneg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blood_group',
            name='Bpos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blood_group',
            name='Oneg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blood_group',
            name='Opos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
