# Generated by Django 4.1.7 on 2023-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_donor_medical_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='medical_records',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
