# Generated by Django 4.1.7 on 2023-04-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_receiver_medical_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='manager_ID',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='staff_ID',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='manager_ID',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='staff_ID',
        ),
    ]
