# Generated by Django 4.1.7 on 2023-04-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AlterField(
            model_name='donor',
            name='city_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
    ]
