# Generated by Django 4.1.7 on 2023-04-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_delete_registration_alter_donor_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_ID',
        ),
    ]
