# Generated by Django 4.1.7 on 2023-04-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_city_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.city'),
        ),
    ]
