# Generated by Django 4.1.7 on 2023-04-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_blood_group_hosp_id_hospital_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='city_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.city'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='city_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.city'),
        ),
    ]
